services:
  - type: web
    name: carpool-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        value: carpool-super-secret-jwt-key-2024-production-grade-change-this
      - key: MONGODB_URI
        value: # Add your MongoDB Atlas connection string here
