services:
  - type: web
    name: carpool-backend
    env: node
    plan: free
    buildCommand: npm ci && cd frontend && npm ci && npm run build
    startCommand: npm run demo
    envVars:
      - key: NODE_ENV
        value: production
